#!/usr/bin/env bash
# =============================================================================
# MeritPay — Soroban Contract Deployment Script
# =============================================================================
# Builds and deploys MeritPay Soroban contracts to Stellar Testnet:
#   1. contracts/groth16_verifier  — payroll batch proof verifier
#   2. contracts/groth16_verifier  — claim proof verifier (second instance)
#   3. contracts/payroll           — payroll pool + batch execution
#   4. contracts/claim             — employee payout claims
#
# Usage:
#   chmod +x scripts/deploy.sh
#   ./scripts/deploy.sh                         # uses 'deployer' identity by default
#
# Or with a different key:
#   DEPLOYER_KEY_NAME=mykey ./scripts/deploy.sh
#
# To create an identity first:
#   stellar keys generate deployer --network testnet
#
# Prerequisites:
#   - Rust stable toolchain with wasm32v1-none target
#   - stellar-cli (https://developers.stellar.org/docs/tools/stellar-cli)
#   - wasm-opt (optional — binaryen, for WASM size optimisation)
#   - ./scripts/setup.sh must have been run (generates vkey.json files)
#
# Outputs:
#   - .env.contracts   — contract IDs for frontend and scripts
# =============================================================================

set -euo pipefail

# ---------------------------------------------------------------------------
# Terminal colours
# ---------------------------------------------------------------------------
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

info()    { echo -e "${CYAN}[INFO]${NC}  $*"; }
success() { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error()   { echo -e "${RED}[ERROR]${NC} $*" >&2; exit 1; }
section() { echo -e "\n${BOLD}${CYAN}━━━  $*  ━━━${NC}"; }

# ---------------------------------------------------------------------------
# Resolve project root
# ---------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$PROJECT_ROOT"

# ---------------------------------------------------------------------------
# Configuration — override via environment variables
# ---------------------------------------------------------------------------
# DEPLOYER_KEY_NAME: name of a locally stored stellar identity (stellar keys ls)
DEPLOYER_KEY_NAME="${DEPLOYER_KEY_NAME:-deployer}"
# DEPLOYER_ADDRESS: public G... address; auto-derived from key name if unset
DEPLOYER_ADDRESS="${DEPLOYER_ADDRESS:-}"
NETWORK="${NETWORK:-testnet}"
NETWORK_RPC="${NETWORK_RPC:-https://soroban-testnet.stellar.org}"
NETWORK_PASSPHRASE="${NETWORK_PASSPHRASE:-Test SDF Network ; September 2015}"

# Initial pool funding: 10 XLM = 100_000_000 stroops
INITIAL_POOL_FUND="${INITIAL_POOL_FUND:-100000000}"

# WASM paths
WASM_DIR="$PROJECT_ROOT/target/wasm32v1-none/release"
VERIFIER_WASM="$WASM_DIR/groth16_verifier.wasm"
PAYROLL_WASM="$WASM_DIR/meritpay_payroll.wasm"
CLAIM_WASM="$WASM_DIR/claim.wasm"
VERIFIER_WASM_OPT="$WASM_DIR/groth16_verifier.opt.wasm"
PAYROLL_WASM_OPT="$WASM_DIR/meritpay_payroll.opt.wasm"
CLAIM_WASM_OPT="$WASM_DIR/claim.opt.wasm"

# Verification keys (generated by setup.sh)
PAYROLL_VKEY="$PROJECT_ROOT/build/payroll/payroll_aggregator_vkey.json"
CLAIM_VKEY="$PROJECT_ROOT/build/claim/claim_vkey.json"

# Output file for contract IDs
ENV_CONTRACTS="$PROJECT_ROOT/.env.contracts"

# =============================================================================
# 1. Prerequisite checks
# =============================================================================
section "1 / 8  Checking prerequisites"

# Check for stellar CLI (may be called 'stellar' or 'soroban' in older versions)
if command -v stellar &>/dev/null; then
    CLI="stellar"
elif command -v soroban &>/dev/null; then
    CLI="soroban"
    warn "'soroban' CLI found; note that the Stellar CLI is the modern replacement."
else
    error "Stellar CLI not found.\n  Install: cargo install --locked stellar-cli --features opt\n  Docs: https://developers.stellar.org/docs/tools/stellar-cli"
fi

STELLAR_VER=$($CLI --version 2>&1 | head -1)
success "$CLI  $STELLAR_VER"

# Check Rust + wasm32 target
if ! command -v cargo &>/dev/null; then
    error "cargo not found. Install Rust: https://rustup.rs"
fi
RUST_VER=$(rustc --version)
success "rustc  $RUST_VER"

if ! rustup target list --installed 2>/dev/null | grep -q "wasm32v1-none"; then
    info "Adding wasm32v1-none target..."
    rustup target add wasm32v1-none
    success "wasm32 target installed"
else
    success "wasm32v1-none target installed"
fi

# Check WASM optimiser (optional)
WASM_OPT_AVAILABLE=false
if command -v wasm-opt &>/dev/null; then
    WASM_OPT_VER=$(wasm-opt --version 2>&1 | head -1)
    success "wasm-opt  $WASM_OPT_VER"
    WASM_OPT_AVAILABLE=true
else
    warn "wasm-opt not found — skipping WASM optimisation (install binaryen for smaller contracts)"
fi

# Validate deployer credentials
# Check the key name exists in the local keystore
if ! $CLI keys ls 2>/dev/null | grep -qx "$DEPLOYER_KEY_NAME"; then
    echo ""
    error "Stellar identity '$DEPLOYER_KEY_NAME' not found.\n\n  To create one:\n    stellar keys generate $DEPLOYER_KEY_NAME --network $NETWORK\n\n  To use an existing key:\n    export DEPLOYER_KEY_NAME=<name>    # from: stellar keys ls"
fi

# Auto-derive address if not supplied
if [[ -z "$DEPLOYER_ADDRESS" ]]; then
    DEPLOYER_ADDRESS=$($CLI keys address "$DEPLOYER_KEY_NAME" 2>/dev/null | xargs)
fi

if [[ -z "$DEPLOYER_ADDRESS" ]]; then
    error "Could not resolve address for key '$DEPLOYER_KEY_NAME'.\n  Set: export DEPLOYER_ADDRESS=G..."
fi

success "Deployer key:     $DEPLOYER_KEY_NAME"
success "Deployer address: $DEPLOYER_ADDRESS"
success "Network: $NETWORK ($NETWORK_RPC)"

# =============================================================================
# 2. Build Soroban contracts
# =============================================================================
section "2 / 8  Building Soroban contracts (Rust → WASM)"

info "Running: cargo build --target wasm32v1-none --release"
cargo build \
    --target wasm32v1-none \
    --release \
    2>&1

if [[ ! -f "$VERIFIER_WASM" ]]; then
    error "groth16_verifier.wasm not found after build.\n  Expected: $VERIFIER_WASM\n  Check that contracts/groth16_verifier/Cargo.toml has the correct package name."
fi

if [[ ! -f "$PAYROLL_WASM" ]]; then
    error "meritpay_payroll.wasm not found after build.\n  Expected: $PAYROLL_WASM"
fi

if [[ ! -f "$CLAIM_WASM" ]]; then
    error "claim.wasm not found after build.\n  Expected: $CLAIM_WASM"
fi

VERIFIER_SIZE=$(du -h "$VERIFIER_WASM" | cut -f1)
PAYROLL_SIZE=$(du -h "$PAYROLL_WASM" | cut -f1)
CLAIM_SIZE=$(du -h "$CLAIM_WASM" | cut -f1)
success "groth16_verifier.wasm  ($VERIFIER_SIZE)"
success "meritpay_payroll.wasm  ($PAYROLL_SIZE)"
success "claim.wasm             ($CLAIM_SIZE)"

# =============================================================================
# 3. Optimise WASM (optional)
# =============================================================================
section "3 / 8  WASM optimisation"

if $WASM_OPT_AVAILABLE; then
    info "Optimising groth16_verifier.wasm..."
    wasm-opt -Os --strip-debug \
        "$VERIFIER_WASM" \
        -o "$VERIFIER_WASM_OPT" \
        2>&1
    OPT_SIZE=$(du -h "$VERIFIER_WASM_OPT" | cut -f1)
    success "groth16_verifier.opt.wasm  ($OPT_SIZE — was $VERIFIER_SIZE)"
    VERIFIER_WASM_DEPLOY="$VERIFIER_WASM_OPT"

    info "Optimising payroll.wasm..."
    wasm-opt -Os --strip-debug \
        "$PAYROLL_WASM" \
        -o "$PAYROLL_WASM_OPT" \
        2>&1
    OPT_SIZE=$(du -h "$PAYROLL_WASM_OPT" | cut -f1)
    success "meritpay_payroll.opt.wasm  ($OPT_SIZE — was $PAYROLL_SIZE)"
    PAYROLL_WASM_DEPLOY="$PAYROLL_WASM_OPT"

    info "Optimising claim.wasm..."
    wasm-opt -Os --strip-debug \
        "$CLAIM_WASM" \
        -o "$CLAIM_WASM_OPT" \
        2>&1
    OPT_SIZE=$(du -h "$CLAIM_WASM_OPT" | cut -f1)
    success "claim.opt.wasm             ($OPT_SIZE — was $CLAIM_SIZE)"
    CLAIM_WASM_DEPLOY="$CLAIM_WASM_OPT"
else
    warn "Skipping WASM optimisation"
    VERIFIER_WASM_DEPLOY="$VERIFIER_WASM"
    PAYROLL_WASM_DEPLOY="$PAYROLL_WASM"
    CLAIM_WASM_DEPLOY="$CLAIM_WASM"
fi

# =============================================================================
# 4. Fund deployer account on testnet
# =============================================================================
section "4 / 8  Funding deployer account on testnet"

info "Requesting testnet funds for $DEPLOYER_KEY_NAME ($DEPLOYER_ADDRESS)..."
$CLI keys fund "$DEPLOYER_KEY_NAME" \
    --network "$NETWORK" \
    2>&1 || warn "Funding request returned non-zero (account may already be funded)"

success "Deployer account funded"

# ---------------------------------------------------------------------------
# Helper: deploy a contract and extract the clean contract ID.
# stellar contract deploy prints status/emoji to stdout along with the ID;
# the ID is always the last 56-character base32 string starting with 'C'.
# ---------------------------------------------------------------------------
deploy_contract() {
    local label="$1"
    local wasm="$2"
    local raw

    raw=$($CLI contract deploy \
        --wasm "$wasm" \
        --network "$NETWORK" \
        --source-account "$DEPLOYER_KEY_NAME" \
        2>&1)

    # Extract the Stellar contract ID (C + 55 uppercase base32 chars = 56 total)
    local id
    id=$(echo "$raw" | grep -oE 'C[A-Z2-7]{55}' | tail -1)

    if [[ -z "$id" ]]; then
        echo "$raw" >&2
        error "Failed to deploy $label — could not extract contract ID from output"
    fi

    echo "$id"
}

# =============================================================================
# 5. Deploy groth16_verifier contract
# =============================================================================
section "5 / 8  Deploying groth16_verifier contract"

info "Uploading and deploying groth16_verifier.wasm to $NETWORK..."
VERIFIER_CONTRACT_ID=$(deploy_contract "groth16_verifier" "$VERIFIER_WASM_DEPLOY")
success "groth16_verifier deployed: $VERIFIER_CONTRACT_ID"

# =============================================================================
# 6. Deploy payroll contract
# =============================================================================
section "6 / 8  Deploying payroll contract"

info "Uploading and deploying payroll.wasm to $NETWORK..."
PAYROLL_CONTRACT_ID=$(deploy_contract "payroll" "$PAYROLL_WASM_DEPLOY")
success "payroll deployed: $PAYROLL_CONTRACT_ID"

# =============================================================================
# 6b. Deploy claim_verifier (second groth16_verifier instance)
# =============================================================================
section "6b / 10  Deploying claim_verifier contract"

info "Uploading and deploying claim_verifier.wasm to $NETWORK..."
CLAIM_VERIFIER_CONTRACT_ID=$(deploy_contract "claim_verifier" "$VERIFIER_WASM_DEPLOY")
success "claim_verifier deployed: $CLAIM_VERIFIER_CONTRACT_ID"

# =============================================================================
# 6c. Deploy claim contract
# =============================================================================
section "6c / 10  Deploying claim contract"

info "Uploading and deploying claim.wasm to $NETWORK..."
CLAIM_CONTRACT_ID=$(deploy_contract "claim" "$CLAIM_WASM_DEPLOY")
success "claim deployed: $CLAIM_CONTRACT_ID"

# Resolve native XLM token contract for the pool
NATIVE_TOKEN="${NATIVE_TOKEN_ADDRESS:-}"
if [[ -z "$NATIVE_TOKEN" ]]; then
    NATIVE_TOKEN=$($CLI contract asset id --network "$NETWORK" --asset native 2>/dev/null | tail -1 | xargs || true)
fi
if [[ -z "$NATIVE_TOKEN" ]]; then
    warn "Could not resolve native XLM token — set NATIVE_TOKEN_ADDRESS and initialize manually"
    NATIVE_TOKEN="$DEPLOYER_ADDRESS"
fi

# =============================================================================
# 7. Initialise contracts
# =============================================================================
section "7 / 10  Initialising contracts"

# 7a. Upload verification keys
if [[ -f "$PAYROLL_VKEY" ]]; then
    info "Uploading payroll VK to groth16_verifier..."
    NEXT_PUBLIC_VERIFIER_CONTRACT_ID="$VERIFIER_CONTRACT_ID" \
        node "$PROJECT_ROOT/scripts/upload_vk.js" "$PAYROLL_VKEY" "$VERIFIER_CONTRACT_ID" \
        2>&1 || warn "Payroll VK upload failed — run: node scripts/upload_vk.js"
else
    warn "Payroll vkey not found at $PAYROLL_VKEY — run ./scripts/setup.sh first"
fi

if [[ -f "$CLAIM_VKEY" ]]; then
    info "Uploading claim VK to claim_verifier..."
    node "$PROJECT_ROOT/scripts/upload_vk.js" "$CLAIM_VKEY" "$CLAIM_VERIFIER_CONTRACT_ID" \
        2>&1 || warn "Claim VK upload failed — run: node scripts/upload_vk.js build/claim/claim_vkey.json $CLAIM_VERIFIER_CONTRACT_ID"
else
    warn "Claim vkey not found at $CLAIM_VKEY — run ./scripts/setup.sh first"
fi

# 7b. Initialise payroll contract
info "Initialising payroll contract..."
$CLI contract invoke \
    --id "$PAYROLL_CONTRACT_ID" \
    --network "$NETWORK" \
    --source-account "$DEPLOYER_KEY_NAME" \
    -- \
    initialize \
    --admin "$DEPLOYER_ADDRESS" \
    --verifier_contract "$VERIFIER_CONTRACT_ID" \
    --token_address "$NATIVE_TOKEN" \
    2>&1 || warn "initialize invocation failed — check contract interface and retry manually"

success "Payroll contract initialised"

# 7c. Initialise claim contract
info "Initialising claim contract..."
$CLI contract invoke \
    --id "$CLAIM_CONTRACT_ID" \
    --network "$NETWORK" \
    --source-account "$DEPLOYER_KEY_NAME" \
    -- \
    initialize \
    --payroll_contract "$PAYROLL_CONTRACT_ID" \
    --verifier_contract "$CLAIM_VERIFIER_CONTRACT_ID" \
    --token_address "$NATIVE_TOKEN" \
    2>&1 || warn "claim initialize failed — retry manually"

success "Claim contract initialised"

# 7d. Link payroll → claim escrow
info "Linking payroll contract to claim escrow..."
$CLI contract invoke \
    --id "$PAYROLL_CONTRACT_ID" \
    --network "$NETWORK" \
    --source-account "$DEPLOYER_KEY_NAME" \
    -- \
    set_claim_contract \
    --admin "$DEPLOYER_ADDRESS" \
    --claim_contract "$CLAIM_CONTRACT_ID" \
    2>&1 || warn "set_claim_contract failed — retry manually"

success "Claim contract linked to payroll"

# 7e. Fund payroll pool with initial XLM
info "Funding payroll pool with $INITIAL_POOL_FUND stroops ($(echo "scale=2; $INITIAL_POOL_FUND / 10000000" | bc) XLM)..."
$CLI contract invoke \
    --id "$PAYROLL_CONTRACT_ID" \
    --network "$NETWORK" \
    --source-account "$DEPLOYER_KEY_NAME" \
    -- \
    fund_pool \
    --funder "$DEPLOYER_ADDRESS" \
    --amount "$INITIAL_POOL_FUND" \
    2>&1 || warn "fund_pool invocation failed — fund the pool manually after deployment"

success "Pool funded with initial XLM"

# =============================================================================
# 8. Save contract IDs and print summary
# =============================================================================
section "8 / 10  Saving deployment artefacts"

cat > "$ENV_CONTRACTS" <<EOF
# MeritPay Contract IDs — generated by scripts/deploy.sh
# Network: $NETWORK
# Deployed: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Deployer: $DEPLOYER_ADDRESS

NEXT_PUBLIC_VERIFIER_CONTRACT_ID=$VERIFIER_CONTRACT_ID
NEXT_PUBLIC_CLAIM_VERIFIER_CONTRACT_ID=$CLAIM_VERIFIER_CONTRACT_ID
NEXT_PUBLIC_PAYROLL_CONTRACT_ID=$PAYROLL_CONTRACT_ID
NEXT_PUBLIC_CLAIM_CONTRACT_ID=$CLAIM_CONTRACT_ID
NEXT_PUBLIC_ADMIN_ADDRESS=$DEPLOYER_ADDRESS
NEXT_PUBLIC_DEPLOYER_ADDRESS=$DEPLOYER_ADDRESS
NEXT_PUBLIC_NETWORK=$NETWORK
NEXT_PUBLIC_NETWORK_RPC=$NETWORK_RPC
EOF

success "Contract IDs saved to .env.contracts"

echo ""
echo -e "${BOLD}${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BOLD}${GREEN}  MeritPay Deployment Complete${NC}"
echo -e "${BOLD}${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "  ${BOLD}Contract IDs:${NC}"
echo    "    groth16_verifier : $VERIFIER_CONTRACT_ID"
echo    "    claim_verifier   : $CLAIM_VERIFIER_CONTRACT_ID"
echo    "    payroll          : $PAYROLL_CONTRACT_ID"
echo    "    claim            : $CLAIM_CONTRACT_ID"
echo    "    network          : $NETWORK"
echo ""
echo -e "  ${BOLD}Explorer links:${NC}"
echo    "    https://stellar.expert/explorer/testnet/contract/$PAYROLL_CONTRACT_ID"
echo    "    https://stellar.expert/explorer/testnet/contract/$CLAIM_CONTRACT_ID"
echo ""
echo -e "  ${BOLD}Next steps:${NC}"
echo    "    cp .env.contracts web/.env.local"
echo    "    cd web && npm install && npm run dev"
echo ""
echo -e "  ${BOLD}Or generate and submit a test proof:${NC}"
echo    "    node scripts/gen_proof.js"
echo ""
